//
// File generated by rootcint at Tue Dec  8 05:37:28 2015

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME nnbarRecoTool_findVertexDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "nnbarRecoTool_findVertexDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
      namespace ertool {

      #if !(defined(R__ACCESS_IN_SYMBOL) || defined(R__USE_SHADOW_CLASS))
      typedef ::ertool::ERAlgofindVertex ERAlgofindVertex;
      #else
      class ERAlgofindVertex  :  public ::ertool::AlgoBase {
         public:
         //friend XX;
         #if !(defined(R__ACCESS_IN_SYMBOL) || defined(R__USE_SHADOW_CLASS))
         typedef ::ertool::ERAlgofindVertex::part part;
         #else
         class part  {
            public:
            //friend XX;
            unsigned long nodeID; //
            ::ertool::RecoType_t recoType; //
            ::TVector3 start; //
            ::TVector3 end; //
         };
         #endif

         // To force the creation of a virtual table, throw just in case.
         virtual ~ERAlgofindVertex() throw() {};
      };
      #endif
      } 
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void ertoolcLcLERAlgofindVertex_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void ertoolcLcLERAlgofindVertex_Dictionary();
   static void *new_ertoolcLcLERAlgofindVertex(void *p = 0);
   static void *newArray_ertoolcLcLERAlgofindVertex(Long_t size, void *p);
   static void delete_ertoolcLcLERAlgofindVertex(void *p);
   static void deleteArray_ertoolcLcLERAlgofindVertex(void *p);
   static void destruct_ertoolcLcLERAlgofindVertex(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::ertool::ERAlgofindVertex*)
   {
      // Make sure the shadow class has the right sizeof
      R__ASSERT(sizeof(::ertool::ERAlgofindVertex) == sizeof( ::ROOTShadow::Shadow::ertool::ERAlgofindVertex));
      ::ertool::ERAlgofindVertex *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::ertool::ERAlgofindVertex),0);
      static ::ROOT::TGenericClassInfo 
         instance("ertool::ERAlgofindVertex", "./ERAlgofindVertex.h", 26,
                  typeid(::ertool::ERAlgofindVertex), ::ROOT::DefineBehavior(ptr, ptr),
                  &ertoolcLcLERAlgofindVertex_ShowMembers, &ertoolcLcLERAlgofindVertex_Dictionary, isa_proxy, 4,
                  sizeof(::ertool::ERAlgofindVertex) );
      instance.SetNew(&new_ertoolcLcLERAlgofindVertex);
      instance.SetNewArray(&newArray_ertoolcLcLERAlgofindVertex);
      instance.SetDelete(&delete_ertoolcLcLERAlgofindVertex);
      instance.SetDeleteArray(&deleteArray_ertoolcLcLERAlgofindVertex);
      instance.SetDestructor(&destruct_ertoolcLcLERAlgofindVertex);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::ertool::ERAlgofindVertex*)
   {
      return GenerateInitInstanceLocal((::ertool::ERAlgofindVertex*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::ertool::ERAlgofindVertex*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void ertoolcLcLERAlgofindVertex_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const ::ertool::ERAlgofindVertex*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

//______________________________________________________________________________
namespace ROOTDict {
   void ertoolcLcLERAlgofindVertex_ShowMembers(void *obj, TMemberInspector &R__insp)
   {
      // Inspect the data members of an object of class ertool::ERAlgofindVertex.
      typedef ::ROOTShadow::Shadow::ertool::ERAlgofindVertex ShadowClass;
      ShadowClass *sobj = (ShadowClass*)obj;
      if (sobj) { } // Dummy usage just in case there is no datamember.

      TClass *R__cl  = ::ROOTDict::GenerateInitInstanceLocal((const ::ertool::ERAlgofindVertex*)0x0)->GetClass();
      if (R__cl || R__insp.IsA()) { }
      R__insp.GenericShowMembers("ertool::AlgoBase", ( ::ertool::AlgoBase * )( (::ertool::ERAlgofindVertex*) obj ), false);
   }

}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_ertoolcLcLERAlgofindVertex(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::ertool::ERAlgofindVertex : new ::ertool::ERAlgofindVertex;
   }
   static void *newArray_ertoolcLcLERAlgofindVertex(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::ertool::ERAlgofindVertex[nElements] : new ::ertool::ERAlgofindVertex[nElements];
   }
   // Wrapper around operator delete
   static void delete_ertoolcLcLERAlgofindVertex(void *p) {
      delete ((::ertool::ERAlgofindVertex*)p);
   }
   static void deleteArray_ertoolcLcLERAlgofindVertex(void *p) {
      delete [] ((::ertool::ERAlgofindVertex*)p);
   }
   static void destruct_ertoolcLcLERAlgofindVertex(void *p) {
      typedef ::ertool::ERAlgofindVertex current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::ertool::ERAlgofindVertex

/********************************************************
* nnbarRecoTool_findVertexDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablennbarRecoTool_findVertexDict();

extern "C" void G__set_cpp_environmentnnbarRecoTool_findVertexDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("ERAlgofindVertex.h");
  G__cpp_reset_tagtablennbarRecoTool_findVertexDict();
}
#include <new>
extern "C" int G__cpp_dllrevnnbarRecoTool_findVertexDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* ertool::ERAlgofindVertex */
static int G__nnbarRecoTool_findVertexDict_635_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   ertool::ERAlgofindVertex* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 1:
     //m: 1
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new ertool::ERAlgofindVertex(*(string*) libp->para[0].ref);
     } else {
       p = new((void*) gvp) ertool::ERAlgofindVertex(*(string*) libp->para[0].ref);
     }
     break;
   case 0:
     int n = G__getaryconstruct();
     if (n) {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new ertool::ERAlgofindVertex[n];
       } else {
         p = new((void*) gvp) ertool::ERAlgofindVertex[n];
       }
     } else {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new ertool::ERAlgofindVertex;
       } else {
         p = new((void*) gvp) ertool::ERAlgofindVertex;
       }
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_ertoolcLcLERAlgofindVertex));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__nnbarRecoTool_findVertexDict_635_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   ertool::ERAlgofindVertex* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new ertool::ERAlgofindVertex(*(ertool::ERAlgofindVertex*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_ertoolcLcLERAlgofindVertex));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef ertool::ERAlgofindVertex G__TertoolcLcLERAlgofindVertex;
static int G__nnbarRecoTool_findVertexDict_635_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (ertool::ERAlgofindVertex*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((ertool::ERAlgofindVertex*) (soff+(sizeof(ertool::ERAlgofindVertex)*i)))->~G__TertoolcLcLERAlgofindVertex();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (ertool::ERAlgofindVertex*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((ertool::ERAlgofindVertex*) (soff))->~G__TertoolcLcLERAlgofindVertex();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__nnbarRecoTool_findVertexDict_635_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   ertool::ERAlgofindVertex* dest = (ertool::ERAlgofindVertex*) G__getstructoffset();
   *dest = *(ertool::ERAlgofindVertex*) libp->para[0].ref;
   const ertool::ERAlgofindVertex& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* ertool::ERAlgofindVertex */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncnnbarRecoTool_findVertexDict {
 public:
  G__Sizep2memfuncnnbarRecoTool_findVertexDict(): p(&G__Sizep2memfuncnnbarRecoTool_findVertexDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncnnbarRecoTool_findVertexDict::*p)();
};

size_t G__get_sizep2memfuncnnbarRecoTool_findVertexDict()
{
  G__Sizep2memfuncnnbarRecoTool_findVertexDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancennbarRecoTool_findVertexDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_ertoolcLcLERAlgofindVertex))) {
     ertool::ERAlgofindVertex *G__Lderived;
     G__Lderived=(ertool::ERAlgofindVertex*)0x1000;
     {
       ertool::AlgoBase *G__Lpbase=(ertool::AlgoBase*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_ertoolcLcLERAlgofindVertex),G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_ertoolcLcLAlgoBase),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       ertool::UnitBase *G__Lpbase=(ertool::UnitBase*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_ertoolcLcLERAlgofindVertex),G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_ertoolcLcLUnitBase),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       ertool::MessageUtil *G__Lpbase=(ertool::MessageUtil*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_ertoolcLcLERAlgofindVertex),G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_ertoolcLcLMessageUtil),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablennbarRecoTool_findVertexDict() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::string>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<PSet::KeyChar_t,size_t>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_pairlEfcllitecLcLPSetcLcLKeyChar_tcOunsignedsPlonggR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,std::string>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,std::string>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,string>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,string,less<string> >",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,::fcllite::PSet>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_maplEstringcOfcllitecLcLPSetcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOfcllitecLcLPSetgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,::fcllite::PSet>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_maplEstringcOfcllitecLcLPSetcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOfcllitecLcLPSetgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,fcllite::PSet>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_maplEstringcOfcllitecLcLPSetcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOfcllitecLcLPSetgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,fcllite::PSet,less<string> >",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_maplEstringcOfcllitecLcLPSetcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOfcllitecLcLPSetgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<size_t,std::string>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_pairlEunsignedsPlongcOstringgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<NodeID_t>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_vectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgR),0,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_ertool));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Combination_t>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_vectorlEvectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgRcOallocatorlEvectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlEvectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgRcOallocatorlEvectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_vectorlEvectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgRcOallocatorlEvectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlEvectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgRcOallocatorlEvectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_vectorlEvectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgRcOallocatorlEvectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<unsigned long,allocator<unsigned long> > >",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_vectorlEvectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgRcOallocatorlEvectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<geoalgo::Vector>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_vectorlEgeoalgocLcLVectorcOallocatorlEgeoalgocLcLVectorgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlEgeoalgocLcLVectorcOallocatorlEgeoalgocLcLVectorgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_vectorlEgeoalgocLcLVectorcOallocatorlEgeoalgocLcLVectorgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlEgeoalgocLcLVectorcOallocatorlEgeoalgocLcLVectorgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_vectorlEgeoalgocLcLVectorcOallocatorlEgeoalgocLcLVectorgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::vector<double> >",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<double> >",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<double,allocator<double> > >",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<geoalgo::Point_t>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_vectorlEgeoalgocLcLVectorcOallocatorlEgeoalgocLcLVectorgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("numeric_limits<size_t>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_numeric_limitslEunsignedsPlonggR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ertool::Shower>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_vectorlEertoolcLcLShowercOallocatorlEertoolcLcLShowergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlEertoolcLcLShowercOallocatorlEertoolcLcLShowergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_vectorlEertoolcLcLShowercOallocatorlEertoolcLcLShowergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlEertoolcLcLShowercOallocatorlEertoolcLcLShowergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_vectorlEertoolcLcLShowercOallocatorlEertoolcLcLShowergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ertool::Track>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_vectorlEertoolcLcLTrackcOallocatorlEertoolcLcLTrackgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlEertoolcLcLTrackcOallocatorlEertoolcLcLTrackgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_vectorlEertoolcLcLTrackcOallocatorlEertoolcLcLTrackgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlEertoolcLcLTrackcOallocatorlEertoolcLcLTrackgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_vectorlEertoolcLcLTrackcOallocatorlEertoolcLcLTrackgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ertool::Flash>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_vectorlEertoolcLcLFlashcOallocatorlEertoolcLcLFlashgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlEertoolcLcLFlashcOallocatorlEertoolcLcLFlashgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_vectorlEertoolcLcLFlashcOallocatorlEertoolcLcLFlashgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlEertoolcLcLFlashcOallocatorlEertoolcLcLFlashgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_vectorlEertoolcLcLFlashcOallocatorlEertoolcLcLFlashgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ertool::RecoInputID_t>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_vectorlEpairlEunsignedsPlongcOstringgRcOallocatorlEpairlEunsignedsPlongcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPlongcOstringgRcOallocatorlEpairlEunsignedsPlongcOstringgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_vectorlEpairlEunsignedsPlongcOstringgRcOallocatorlEpairlEunsignedsPlongcOstringgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPlongcOstringgRcOallocatorlEpairlEunsignedsPlongcOstringgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_vectorlEpairlEunsignedsPlongcOstringgRcOallocatorlEpairlEunsignedsPlongcOstringgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<unsigned long,string> >",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_vectorlEpairlEunsignedsPlongcOstringgRcOallocatorlEpairlEunsignedsPlongcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<::ertool::NodeID_t>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_vectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("deque<::ertool::Particle>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_dequelEertoolcLcLParticlecOallocatorlEertoolcLcLParticlegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("deque<ertool::Particle>",117,G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_dequelEertoolcLcLParticlecOallocatorlEertoolcLcLParticlegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* ertool::ERAlgofindVertex */
static void G__setup_memvarertoolcLcLERAlgofindVertex(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_ertoolcLcLERAlgofindVertex));
   { ertool::ERAlgofindVertex *p; p=(ertool::ERAlgofindVertex*)0x1000; if (p) { }
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarnnbarRecoTool_findVertexDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncertoolcLcLERAlgofindVertex(void) {
   /* ertool::ERAlgofindVertex */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_ertoolcLcLERAlgofindVertex));
   G__memfunc_setup("ERAlgofindVertex",1593,G__nnbarRecoTool_findVertexDict_635_0_1, 105, G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_ertoolcLcLERAlgofindVertex), -1, 0, 1, 1, 1, 0, "u 'string' - 11 '\"ERAlgofindVertex\"' name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Reset",515,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("AcceptPSet",972,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'fcllite::PSet' - 11 - cfg", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ProcessBegin",1220,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Reconstruct",1180,(G__InterfaceMethod) NULL,103, -1, -1, 0, 2, 1, 1, 0, 
"u 'ertool::EventData' - 11 - data u 'ertool::ParticleGraph' - 1 - graph", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ProcessEnd",1014,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "U 'TFile' - 0 'nullptr' fout", (char*)NULL, (void*) NULL, 1);
   // automatic copy constructor
   G__memfunc_setup("ERAlgofindVertex", 1593, G__nnbarRecoTool_findVertexDict_635_0_7, (int) ('i'), G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_ertoolcLcLERAlgofindVertex), -1, 0, 1, 1, 1, 0, "u 'ertool::ERAlgofindVertex' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~ERAlgofindVertex", 1719, G__nnbarRecoTool_findVertexDict_635_0_8, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__nnbarRecoTool_findVertexDict_635_0_9, (int) ('u'), G__get_linked_tagnum(&G__nnbarRecoTool_findVertexDictLN_ertoolcLcLERAlgofindVertex), -1, 1, 1, 1, 1, 0, "u 'ertool::ERAlgofindVertex' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncnnbarRecoTool_findVertexDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalnnbarRecoTool_findVertexDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
}

static void G__cpp_setup_func25() {
}

static void G__cpp_setup_func26() {
}

static void G__cpp_setup_func27() {
}

static void G__cpp_setup_func28() {
}

static void G__cpp_setup_func29() {
}

static void G__cpp_setup_func30() {
}

static void G__cpp_setup_func31() {
}

static void G__cpp_setup_func32() {
}

static void G__cpp_setup_func33() {
}

static void G__cpp_setup_func34() {
}

static void G__cpp_setup_func35() {
}

static void G__cpp_setup_func36() {
}

static void G__cpp_setup_func37() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcnnbarRecoTool_findVertexDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
  G__cpp_setup_func25();
  G__cpp_setup_func26();
  G__cpp_setup_func27();
  G__cpp_setup_func28();
  G__cpp_setup_func29();
  G__cpp_setup_func30();
  G__cpp_setup_func31();
  G__cpp_setup_func32();
  G__cpp_setup_func33();
  G__cpp_setup_func34();
  G__cpp_setup_func35();
  G__cpp_setup_func36();
  G__cpp_setup_func37();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_vectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgR = { "vector<unsigned long,allocator<unsigned long> >" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_TFile = { "TFile" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_fcllite = { "fcllite" , 110 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_vectorlEstringcOallocatorlEstringgRsPgR = { "vector<string,allocator<string> >" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<string,allocator<string> >::iterator>" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_fcllitecLcLPSet = { "fcllite::PSet" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_pairlEfcllitecLcLPSetcLcLKeyChar_tcOunsignedsPlonggR = { "pair<fcllite::PSet::KeyChar_t,unsigned long>" , 115 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR = { "map<string,string,less<string>,allocator<pair<const string,string> > >" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_maplEstringcOfcllitecLcLPSetcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOfcllitecLcLPSetgRsPgRsPgR = { "map<string,fcllite::PSet,less<string>,allocator<pair<const string,fcllite::PSet> > >" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_ertool = { "ertool" , 110 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_pairlEunsignedsPlongcOstringgR = { "pair<unsigned long,string>" , 115 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_vectorlEvectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgRcOallocatorlEvectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgRsPgRsPgR = { "vector<vector<unsigned long,allocator<unsigned long> >,allocator<vector<unsigned long,allocator<unsigned long> > > >" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlEvectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgRcOallocatorlEvectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<unsigned long,allocator<unsigned long> >,allocator<vector<unsigned long,allocator<unsigned long> > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_ertoolcLcLMessageUtil = { "ertool::MessageUtil" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_ertoolcLcLUnitBase = { "ertool::UnitBase" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_numeric_limitslEunsignedsPlonggR = { "numeric_limits<unsigned long>" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_vectorlEgeoalgocLcLVectorcOallocatorlEgeoalgocLcLVectorgRsPgR = { "vector<geoalgo::Vector,allocator<geoalgo::Vector> >" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlEgeoalgocLcLVectorcOallocatorlEgeoalgocLcLVectorgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<geoalgo::Vector,allocator<geoalgo::Vector> >::iterator>" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR = { "vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_ertoolcLcLEventData = { "ertool::EventData" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_vectorlEertoolcLcLShowercOallocatorlEertoolcLcLShowergRsPgR = { "vector<ertool::Shower,allocator<ertool::Shower> >" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlEertoolcLcLShowercOallocatorlEertoolcLcLShowergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ertool::Shower,allocator<ertool::Shower> >::iterator>" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_vectorlEertoolcLcLTrackcOallocatorlEertoolcLcLTrackgRsPgR = { "vector<ertool::Track,allocator<ertool::Track> >" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlEertoolcLcLTrackcOallocatorlEertoolcLcLTrackgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ertool::Track,allocator<ertool::Track> >::iterator>" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_vectorlEertoolcLcLFlashcOallocatorlEertoolcLcLFlashgRsPgR = { "vector<ertool::Flash,allocator<ertool::Flash> >" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlEertoolcLcLFlashcOallocatorlEertoolcLcLFlashgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ertool::Flash,allocator<ertool::Flash> >::iterator>" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_vectorlEpairlEunsignedsPlongcOstringgRcOallocatorlEpairlEunsignedsPlongcOstringgRsPgRsPgR = { "vector<pair<unsigned long,string>,allocator<pair<unsigned long,string> > >" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPlongcOstringgRcOallocatorlEpairlEunsignedsPlongcOstringgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<unsigned long,string>,allocator<pair<unsigned long,string> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_ertoolcLcLParticleGraph = { "ertool::ParticleGraph" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_dequelEertoolcLcLParticlecOallocatorlEertoolcLcLParticlegRsPgR = { "deque<ertool::Particle,allocator<ertool::Particle> >" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_ertoolcLcLAlgoBase = { "ertool::AlgoBase" , 99 , -1 };
G__linked_taginfo G__nnbarRecoTool_findVertexDictLN_ertoolcLcLERAlgofindVertex = { "ertool::ERAlgofindVertex" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablennbarRecoTool_findVertexDict() {
  G__nnbarRecoTool_findVertexDictLN_vectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgR.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_string.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_TFile.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_fcllite.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_vectorlEstringcOallocatorlEstringgRsPgR.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_fcllitecLcLPSet.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_pairlEfcllitecLcLPSetcLcLKeyChar_tcOunsignedsPlonggR.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_maplEstringcOfcllitecLcLPSetcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOfcllitecLcLPSetgRsPgRsPgR.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_ertool.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_pairlEunsignedsPlongcOstringgR.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_vectorlEvectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgRcOallocatorlEvectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgRsPgRsPgR.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlEvectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgRcOallocatorlEvectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_ertoolcLcLMessageUtil.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_ertoolcLcLUnitBase.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_numeric_limitslEunsignedsPlonggR.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_vectorlEgeoalgocLcLVectorcOallocatorlEgeoalgocLcLVectorgRsPgR.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlEgeoalgocLcLVectorcOallocatorlEgeoalgocLcLVectorgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_ertoolcLcLEventData.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_vectorlEertoolcLcLShowercOallocatorlEertoolcLcLShowergRsPgR.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlEertoolcLcLShowercOallocatorlEertoolcLcLShowergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_vectorlEertoolcLcLTrackcOallocatorlEertoolcLcLTrackgRsPgR.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlEertoolcLcLTrackcOallocatorlEertoolcLcLTrackgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_vectorlEertoolcLcLFlashcOallocatorlEertoolcLcLFlashgRsPgR.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlEertoolcLcLFlashcOallocatorlEertoolcLcLFlashgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_vectorlEpairlEunsignedsPlongcOstringgRcOallocatorlEpairlEunsignedsPlongcOstringgRsPgRsPgR.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPlongcOstringgRcOallocatorlEpairlEunsignedsPlongcOstringgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_ertoolcLcLParticleGraph.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_dequelEertoolcLcLParticlecOallocatorlEertoolcLcLParticlegRsPgR.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_ertoolcLcLAlgoBase.tagnum = -1 ;
  G__nnbarRecoTool_findVertexDictLN_ertoolcLcLERAlgofindVertex.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablennbarRecoTool_findVertexDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_vectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgR);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_string);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_TFile);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_fcllite);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_vectorlEstringcOallocatorlEstringgRsPgR);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_fcllitecLcLPSet);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_pairlEfcllitecLcLPSetcLcLKeyChar_tcOunsignedsPlonggR);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_maplEstringcOfcllitecLcLPSetcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOfcllitecLcLPSetgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_ertool);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_pairlEunsignedsPlongcOstringgR);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_vectorlEvectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgRcOallocatorlEvectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlEvectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgRcOallocatorlEvectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_ertoolcLcLMessageUtil);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_ertoolcLcLUnitBase);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_numeric_limitslEunsignedsPlonggR);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_TMatrixTSparseDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_vectorlEgeoalgocLcLVectorcOallocatorlEgeoalgocLcLVectorgRsPgR);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlEgeoalgocLcLVectorcOallocatorlEgeoalgocLcLVectorgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_ertoolcLcLEventData);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_vectorlEertoolcLcLShowercOallocatorlEertoolcLcLShowergRsPgR);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlEertoolcLcLShowercOallocatorlEertoolcLcLShowergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_vectorlEertoolcLcLTrackcOallocatorlEertoolcLcLTrackgRsPgR);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlEertoolcLcLTrackcOallocatorlEertoolcLcLTrackgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_vectorlEertoolcLcLFlashcOallocatorlEertoolcLcLFlashgRsPgR);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlEertoolcLcLFlashcOallocatorlEertoolcLcLFlashgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_vectorlEpairlEunsignedsPlongcOstringgRcOallocatorlEpairlEunsignedsPlongcOstringgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPlongcOstringgRcOallocatorlEpairlEunsignedsPlongcOstringgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_ertoolcLcLParticleGraph);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_dequelEertoolcLcLParticlecOallocatorlEertoolcLcLParticlegRsPgR);
   G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_ertoolcLcLAlgoBase);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__nnbarRecoTool_findVertexDictLN_ertoolcLcLERAlgofindVertex),sizeof(ertool::ERAlgofindVertex),-1,263424,(char*)NULL,G__setup_memvarertoolcLcLERAlgofindVertex,G__setup_memfuncertoolcLcLERAlgofindVertex);
}
extern "C" void G__cpp_setupnnbarRecoTool_findVertexDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupnnbarRecoTool_findVertexDict()");
  G__set_cpp_environmentnnbarRecoTool_findVertexDict();
  G__cpp_setup_tagtablennbarRecoTool_findVertexDict();

  G__cpp_setup_inheritancennbarRecoTool_findVertexDict();

  G__cpp_setup_typetablennbarRecoTool_findVertexDict();

  G__cpp_setup_memvarnnbarRecoTool_findVertexDict();

  G__cpp_setup_memfuncnnbarRecoTool_findVertexDict();
  G__cpp_setup_globalnnbarRecoTool_findVertexDict();
  G__cpp_setup_funcnnbarRecoTool_findVertexDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncnnbarRecoTool_findVertexDict();
  return;
}
class G__cpp_setup_initnnbarRecoTool_findVertexDict {
  public:
    G__cpp_setup_initnnbarRecoTool_findVertexDict() { G__add_setup_func("nnbarRecoTool_findVertexDict",(G__incsetup)(&G__cpp_setupnnbarRecoTool_findVertexDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initnnbarRecoTool_findVertexDict() { G__remove_setup_func("nnbarRecoTool_findVertexDict"); }
};
G__cpp_setup_initnnbarRecoTool_findVertexDict G__cpp_setup_initializernnbarRecoTool_findVertexDict;

