/********************************************************************
* nnbarRecoTool_nnbarRecoToolDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error nnbarRecoTool_nnbarRecoToolDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablennbarRecoTool_nnbarRecoToolDict();
extern void G__cpp_setup_inheritancennbarRecoTool_nnbarRecoToolDict();
extern void G__cpp_setup_typetablennbarRecoTool_nnbarRecoToolDict();
extern void G__cpp_setup_memvarnnbarRecoTool_nnbarRecoToolDict();
extern void G__cpp_setup_globalnnbarRecoTool_nnbarRecoToolDict();
extern void G__cpp_setup_memfuncnnbarRecoTool_nnbarRecoToolDict();
extern void G__cpp_setup_funcnnbarRecoTool_nnbarRecoToolDict();
extern void G__set_cpp_environmentnnbarRecoTool_nnbarRecoToolDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "sample.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__nnbarRecoTool_nnbarRecoToolDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__nnbarRecoTool_nnbarRecoToolDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__nnbarRecoTool_nnbarRecoToolDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__nnbarRecoTool_nnbarRecoToolDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__nnbarRecoTool_nnbarRecoToolDictLN_sample;

/* STUB derived class for protected member access */
